// <auto-generated />
namespace AirlineServices.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class passenger_createdate_field : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(passenger_createdate_field));
        
        string IMigrationMetadata.Id
        {
            get { return "201411170128571_passenger_createdate_field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
